# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=30)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=80)),
                ('person_name', models.CharField(max_length=80)),
                ('company_name', models.CharField(max_length=80)),
                ('website', models.URLField()),
                ('country', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('skype', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(max_length=300)),
                ('exibition', models.CharField(max_length=50)),
                ('contacted_on', models.DateField()),
                ('action_date', models.DateField()),
                ('account_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Customer'),
        ),
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
