# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 07:11
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20170513_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
