# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20170519_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contacted_on',
            field=models.DateField(blank=True, null=True, verbose_name='Last contact'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='person_name',
            field=models.CharField(max_length=80, verbose_name='Name and Surname'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, verbose_name='WWW'),
        ),
    ]
