# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20170522_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=80, unique=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, unique=True, verbose_name='WWW'),
        ),
    ]
