# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20170524_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=3000),
        ),
    ]
