# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20170525_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['company_name'], 'permissions': (('view_customer', 'Can see individual contact'), ('view_all_customers', 'Can view a table with all contacts')), 'verbose_name_plural': 'customers'},
        ),
    ]
