# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 09:16
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20170529_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
