# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_auto_20170530_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'permissions': (('view_sport', 'Can see individual sport record'), ('view_all_sports', 'Can view a table with all sports'))},
        ),
    ]
